-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 09:40:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adress` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `floor` VARCHAR(45) NULL,
  `door` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `id_supplier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `fax` VARCHAR(32) NULL,
  `nif` VARCHAR(45) NOT NULL,
  `adress_id` INT NOT NULL,
  PRIMARY KEY (`id_supplier`, `adress_id`),
  INDEX `fk_supplier_adress_idx` (`adress_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_adress`
    FOREIGN KEY (`adress_id`)
    REFERENCES `mydb`.`adress` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `supplier_id_supplier` INT NOT NULL,
  `supplier_adress_id` INT NOT NULL,
  PRIMARY KEY (`id_brand`, `supplier_id_supplier`, `supplier_adress_id`),
  INDEX `fk_brand_supplier1_idx` (`supplier_id_supplier` ASC, `supplier_adress_id` ASC) VISIBLE,
  CONSTRAINT `fk_brand_supplier1`
    FOREIGN KEY (`supplier_id_supplier` , `supplier_adress_id`)
    REFERENCES `mydb`.`supplier` (`id_supplier` , `adress_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`costumer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`costumer` (
  `id_costumer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `date_register` DATE NOT NULL,
  `costumer_recomended_id` INT NULL,
  PRIMARY KEY (`id_costumer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`worker` (
  `id_worker` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_worker`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice` (
  `id_invoice` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `costumer_id` INT NOT NULL,
  `worker_id` INT NOT NULL,
  PRIMARY KEY (`id_invoice`),
  INDEX `id_costumer_idx` (`costumer_id` ASC) VISIBLE,
  INDEX `fk_invoice_worker1_idx` (`worker_id` ASC) VISIBLE,
  CONSTRAINT `id_costumer`
    FOREIGN KEY (`costumer_id`)
    REFERENCES `mydb`.`costumer` (`id_costumer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_invoice_worker1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `mydb`.`worker` (`id_worker`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glasses` (
  `id_glasses` INT NOT NULL AUTO_INCREMENT,
  `graduation` FLOAT NOT NULL,
  `glasses_frame` ENUM('floating', 'pasta', 'metal') NOT NULL,
  `color_frame` VARCHAR(45) NOT NULL,
  `color_lens` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`id_glasses`),
  INDEX `id_brand_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `id_brand`
    FOREIGN KEY (`brand_id`)
    REFERENCES `mydb`.`brand` (`id_brand`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`glasses_has_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glasses_has_invoice` (
  `id_invoice_details` INT NOT NULL AUTO_INCREMENT,
  `glasses_id_glasses` INT NOT NULL,
  `invoice_id_invoice` INT NOT NULL,
  INDEX `fk_glasses_has_invoice_invoice1_idx` (`invoice_id_invoice` ASC) VISIBLE,
  INDEX `fk_glasses_has_invoice_glasses1_idx` (`glasses_id_glasses` ASC) VISIBLE,
  PRIMARY KEY (`id_invoice_details`),
  CONSTRAINT `fk_glasses_has_invoice_glasses1`
    FOREIGN KEY (`glasses_id_glasses`)
    REFERENCES `mydb`.`glasses` (`id_glasses`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_glasses_has_invoice_invoice1`
    FOREIGN KEY (`invoice_id_invoice`)
    REFERENCES `mydb`.`invoice` (`id_invoice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
