-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 09:31:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema S2_N1_EX2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema S2_N1_EX2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `S2_N1_EX2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish2_ci ;
USE `S2_N1_EX2` ;

-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`province` (
  `id_province` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_province`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`city` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id_city`),
  INDEX `province_id_idx` (`province_id` ASC),
  CONSTRAINT `province_id`
    FOREIGN KEY (`province_id`)
    REFERENCES `S2_N1_EX2`.`province` (`id_province`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`shop` (
  `id_shop` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `post_code` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  `province_id` INT NULL,
  PRIMARY KEY (`id_shop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`worker_delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`worker_delivery` (
  `id_worker` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `shop_id_shop` INT NOT NULL,
  PRIMARY KEY (`id_worker`, `shop_id_shop`),
  INDEX `fk_worker_delivery_shop1_idx` (`shop_id_shop` ASC),
  CONSTRAINT `fk_worker_delivery_shop1`
    FOREIGN KEY (`shop_id_shop`)
    REFERENCES `S2_N1_EX2`.`shop` (`id_shop`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `date/time` DATETIME NOT NULL,
  `delivery_type` ENUM('home_delivry', 'local') NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `worker_id` INT NOT NULL,
  `date_time_delivery` VARCHAR(45) NOT NULL,
  `quantity_of` VARCHAR(45) NULL,
  `shop_id_shop` INT NOT NULL,
  `worker_delivery_id_worker` INT NOT NULL,
  `worker_delivery_shop_id_shop` INT NOT NULL,
  PRIMARY KEY (`id_order`, `shop_id_shop`, `worker_delivery_id_worker`, `worker_delivery_shop_id_shop`),
  INDEX `fk_order_shop1_idx` (`shop_id_shop` ASC),
  INDEX `fk_order_worker_delivery1_idx` (`worker_delivery_id_worker` ASC, `worker_delivery_shop_id_shop` ASC),
  CONSTRAINT `fk_order_shop1`
    FOREIGN KEY (`shop_id_shop`)
    REFERENCES `S2_N1_EX2`.`shop` (`id_shop`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_worker_delivery1`
    FOREIGN KEY (`worker_delivery_id_worker` , `worker_delivery_shop_id_shop`)
    REFERENCES `S2_N1_EX2`.`worker_delivery` (`id_worker` , `shop_id_shop`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`costumer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`costumer` (
  `id_costumer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NULL,
  `address` VARCHAR(45) NOT NULL,
  `post_code` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  `province_id` INT NOT NULL,
  `city_id_city` INT NOT NULL,
  `order_id_order` INT NOT NULL,
  PRIMARY KEY (`id_costumer`, `city_id_city`, `order_id_order`),
  INDEX `fk_costumer_city1_idx` (`city_id_city` ASC),
  INDEX `fk_costumer_order1_idx` (`order_id_order` ASC),
  CONSTRAINT `fk_costumer_city1`
    FOREIGN KEY (`city_id_city`)
    REFERENCES `S2_N1_EX2`.`city` (`id_city`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_costumer_order1`
    FOREIGN KEY (`order_id_order`)
    REFERENCES `S2_N1_EX2`.`order` (`id_order`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`worker_cooker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`worker_cooker` (
  `id_worker` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `shop_id_shop` INT NOT NULL,
  PRIMARY KEY (`id_worker`, `shop_id_shop`),
  INDEX `fk_worker_cooker_shop1_idx` (`shop_id_shop` ASC),
  CONSTRAINT `fk_worker_cooker_shop1`
    FOREIGN KEY (`shop_id_shop`)
    REFERENCES `S2_N1_EX2`.`shop` (`id_shop`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`pizza_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`pizza_category` (
  `id_pizza_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pizza_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`pizza` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NULL,
  `price` FLOAT NOT NULL,
  `pizza_category_id` INT NOT NULL,
  `order_id_order` INT NOT NULL,
  `order_shop_id_shop` INT NOT NULL,
  PRIMARY KEY (`id_pizza`, `order_id_order`, `order_shop_id_shop`),
  INDEX `pizza_category_id_idx` (`pizza_category_id` ASC),
  INDEX `fk_pizza_order1_idx` (`order_id_order` ASC, `order_shop_id_shop` ASC),
  CONSTRAINT `pizza_category_id`
    FOREIGN KEY (`pizza_category_id`)
    REFERENCES `S2_N1_EX2`.`pizza_category` (`id_pizza_category`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pizza_order1`
    FOREIGN KEY (`order_id_order` , `order_shop_id_shop`)
    REFERENCES `S2_N1_EX2`.`order` (`id_order` , `shop_id_shop`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`hambuerguer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`hambuerguer` (
  `id_hamburguer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NULL,
  `price` FLOAT NOT NULL,
  `order_id_order` INT NOT NULL,
  `order_shop_id_shop` INT NOT NULL,
  PRIMARY KEY (`id_hamburguer`, `order_id_order`, `order_shop_id_shop`),
  INDEX `fk_hambuerguer_order1_idx` (`order_id_order` ASC, `order_shop_id_shop` ASC),
  CONSTRAINT `fk_hambuerguer_order1`
    FOREIGN KEY (`order_id_order` , `order_shop_id_shop`)
    REFERENCES `S2_N1_EX2`.`order` (`id_order` , `shop_id_shop`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S2_N1_EX2`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S2_N1_EX2`.`drink` (
  `id_drink` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NULL,
  `price` FLOAT NOT NULL,
  `order_id_order` INT NOT NULL,
  `order_shop_id_shop` INT NOT NULL,
  PRIMARY KEY (`id_drink`, `order_id_order`, `order_shop_id_shop`),
  INDEX `fk_drink_order1_idx` (`order_id_order` ASC, `order_shop_id_shop` ASC),
  CONSTRAINT `fk_drink_order1`
    FOREIGN KEY (`order_id_order` , `order_shop_id_shop`)
    REFERENCES `S2_N1_EX2`.`order` (`id_order` , `shop_id_shop`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
